---
- name: Run left examples to illustrate 'Liskov substitution' principle in ansible
  hosts: all
  gather_facts: false
  vars: {}
  tasks:
    - name: Show copyright
      solid.example.show_c:
      run_once: true

    - name: Show warranty
      solid.example.show_w:
      run_once: true

    - name: Run liskov_substitution role
      ansible.builtin.include_role:
        name: solid.example.liskov_substitution
      vars:
        liskov_substitution_param: This will run as it suppose to
